FrontBundle_default:
    resource: "@FrontBundle/Resources/config/routing/default.yml"
    prefix:   /

AppBundle_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix:   /
    
AppBundle_article:
    resource: "@AppBundle/Resources/config/routing/article.yml"
    prefix:   /articulos

AppBundle_category:
    resource: "@AppBundle/Resources/config/routing/category.yml"
    prefix:   /categorias

    
AppBundle_product:
    resource: "@AppBundle/Resources/config/routing/product.yml"
    prefix:   /productos
